# Generated by Django 4.2.1 on 2023-06-09 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="cateogry",
            new_name="category",
        ),
    ]
